name: Ruby on Rails CI

on:
  push:
    branches: [ master ]
  pull_request:
    branches: [ master ]

jobs:
  build:
    runs-on: ubuntu-latest

    steps:
    - uses: actions/checkout@v4.1.1

    - name: Set up Ruby
      uses: ruby/setup-ruby@v1
      with:
        ruby-version: '3.3' # Specify your Ruby version

    - name: Install dependencies
      run: |
        gem install bundler
        bundle install --jobs 4 --retry 3

    - name: Set up Database
      run: |
        cp config/database.yml.ci config/database.yml
        bundle exec rake db:create db:migrate RAILS_ENV=test

    - name: Run Tests
      run: bundle exec rake test
